language: node_js
node_js:
  - 6.10.0

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli@1.0.0-rc.1

script:
  - ng test --watch false

notifications:
  email:
    on_failure: change
    on_success: change